/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nonkululekombatha.resourcemanagementapp;

/**
 *
 * @author mbath
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorModule
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        HomeLabel = new javax.swing.JLabel();
        AdminModuleBtn = new javax.swing.JButton();
        FacultyModuleBtn = new javax.swing.JButton();
        StudentModuleBtn = new javax.swing.JButton();
        DeptModuleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setBackground(new java.awt.Color(153, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HomeLabel.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(0, 153, 153));
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home Navigation");

        AdminModuleBtn.setBackground(new java.awt.Color(0, 153, 153));
        AdminModuleBtn.setFont(new java.awt.Font("Agency FB", 2, 18)); // NOI18N
        AdminModuleBtn.setForeground(new java.awt.Color(51, 51, 51));
        AdminModuleBtn.setText("Administration");
        AdminModuleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AdminModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminModuleBtnActionPerformed(evt);
            }
        });

        FacultyModuleBtn.setBackground(new java.awt.Color(0, 153, 153));
        FacultyModuleBtn.setFont(new java.awt.Font("Agency FB", 2, 18)); // NOI18N
        FacultyModuleBtn.setForeground(new java.awt.Color(51, 51, 51));
        FacultyModuleBtn.setText("Faculty");
        FacultyModuleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FacultyModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyModuleBtnActionPerformed(evt);
            }
        });

        StudentModuleBtn.setBackground(new java.awt.Color(0, 153, 153));
        StudentModuleBtn.setFont(new java.awt.Font("Agency FB", 2, 18)); // NOI18N
        StudentModuleBtn.setForeground(new java.awt.Color(51, 51, 51));
        StudentModuleBtn.setText("Student Info");
        StudentModuleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StudentModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentModuleBtnActionPerformed(evt);
            }
        });

        DeptModuleBtn.setBackground(new java.awt.Color(0, 153, 153));
        DeptModuleBtn.setFont(new java.awt.Font("Agency FB", 2, 18)); // NOI18N
        DeptModuleBtn.setForeground(new java.awt.Color(51, 51, 51));
        DeptModuleBtn.setText("Department(s)");
        DeptModuleBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeptModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptModuleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(HomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StudentModuleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FacultyModuleBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AdminModuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(DeptModuleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(HomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(AdminModuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FacultyModuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StudentModuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeptModuleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeptModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptModuleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptModuleBtnActionPerformed

    private void FacultyModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyModuleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultyModuleBtnActionPerformed

    private void StudentModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentModuleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentModuleBtnActionPerformed

    private void AdminModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminModuleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminModuleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminModuleBtn;
    private javax.swing.JButton DeptModuleBtn;
    private javax.swing.JButton FacultyModuleBtn;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JButton StudentModuleBtn;
    private javax.swing.JColorChooser jColorChooser1;
    // End of variables declaration//GEN-END:variables
}
